### ISSUE TITLE
What is the `source` prop in this line?

### ISSUE THREAD

**Issue by frederikhors** [storybookjs/addon-svelte-csf#14]
What is the `source` prop in the line below (from Readme)?

`<Story name="Square" source args={{rounded: false}}/>`

**Comment by j3rem1e** [comment]
In Storybook v6.2, svelte sources snippet for args story is auto-generated. This option allows to configure that.

With this addon:
- For non args story, sources are extracted from the stories, between `<Story>source</Story>`
- For args story, sources are auto-generated is the property source is false (or unset)
- If source is set to true, then sources are extracted from the stories
- If source is a string, it's used as the story sources

Yes, I know, the documentation is very light yet, it's a WiP ^^ That's said, you should probably ask your question on discord in the #svelte channel instead of here.

**Comment by frederikhors** [comment]
Thanks. I opened https://github.com/storybookjs/addon-svelte-csf/issues/16.
