### ISSUE TITLE
[Bug] Using Svelte CSF with Storyshots fail: "SyntaxError: Unexpected token '<'"

### ISSUE THREAD

**Issue by cmellinas** [storybookjs/addon-svelte-csf#37]
Hi, 

I tried to setup a project using both Svelte CSF and Storyshots and got errors during integration.

I saw that this project contained an example, so I cloned it and made some tests.

### Describe the bug

I ran into a strange bug with my cloned repository.

If I launch npm run test, it worked well initially.

So I tried a more advanced test, I tried to replace:
**import { Meta, Story } from '../src/index.js';**
by
**import { Meta, Story } from '@storybook/addon-svelte-csf';** (version 1.1.0)

Just doing that, generated strange issues: "SyntaxError: Unexpected token '<'"

And the Storyshot for the Story in error was not generated.

### Steps to reproduce the behavior

Here my cloned repository and my commit to reproduce this strange behaviour:
https://github.com/cmellinas/addon-svelte-csf/commit/7202f41bf1dcff77d4dfa57209d6715abb916988

### Expected behavior

Storyshots should work the same way with npm library and local import.

### Environment

 - OS: MacOS
 - Node.js version: v14.16.0
 - NPM version: 6.14.11

Do I need to setup something specific for Storyshot to make Svelte CSF addon work ?

I tried this:
https://github.com/storybookjs/storybook/tree/main/addons/storyshots/storyshots-core#testing-stories-that-rely-on-addon-added-decorators

But I didn't find a solution to make it work correctly.

Thanks,

**Comment by brittneypostma** [comment]
Same bug experienced today when generating a storybook app with `npx sb@next init` and fixing the cjs/esm errors.

**Comment by jonniebigodes** [comment]
@brittneypostma sorry for the late response on this, it seems to be the case. To give you a bit of context, this addon was a bit of an experiment created by one of our contributors, thankfully it matured to a point that could be added into Storybook installations. But as of late we need a bit of help with this addon, not only in maintaining it but improving as there are some features that require attention. If you're willing to contribute we'd appreciate it, or if you know someone in the Svelte community that can help us let us know so that we can follow up and continue supporting this addon.

Would love to hear your thoughts on this and possibly follow up with you!

Have a great day!

Stay safe

**Comment by j3rem1e** [comment]
Can I have a repro on this issue ?

This repo uses storyshots, and it works correctly. Storyshots works has expected in my own repo too.

**Comment by giuxtaposition** [comment]
@cmellinas,
jest by defaults ignore files in node_modules while doing his transformations. That's why you received the syntax error.

You can fix this by adding `transformIgnorePatterns: ['<rootDir>/node_modules/(?!(@storybook/(svelte|addon-svelte-csf))/)']` to your jest config. 
It tells jest to ignore all files inside `/node_modules` except `@storybook/svelte` and `@storybook/addon-svelte-csf`

You can read more about it in the [jest documentation](https://jestjs.io/docs/configuration#transformignorepatterns-arraystring)
I was able to successfully use svelte csf with storyshots on my personal project [here](https://github.com/giuxtaposition/startpage) if you want to take a look.

**Comment by mendokusan** [comment]
I tried the jest solution and I am still facing the same issue. I was wondering is there any new updates on this issue? Would be appreciated.

**Comment by cbishop-fv** [comment]
> @cmellinas, jest by defaults ignore files in node_modules while doing his transformations. That's why you received the syntax error.
> 
> You can fix this by adding `transformIgnorePatterns: ['<rootDir>/node_modules/(?!(@storybook/(svelte|addon-svelte-csf))/)']` to your jest config. It tells jest to ignore all files inside `/node_modules` except `@storybook/svelte` and `@storybook/addon-svelte-csf`
> 
> You can read more about it in the [jest documentation](https://jestjs.io/docs/configuration#transformignorepatterns-arraystring) I was able to successfully use svelte csf with storyshots on my personal project [here](https://github.com/giuxtaposition/startpage) if you want to take a look.

We ran into this same issue. I was trying to do a similar fix adding it to transformIgnorPatterns and got it working.

**Comment by benmccann** [comment]
The error message indicates that the Svelte compiler wasn't being called or was being called twice - I forget which. This is a pretty old issue. I'm guessing it's fixed now. Does it still happen with the latest versions of Storybook and the plugins? If so, can you provide an updated reproduction?

**Comment by brittneypostma** [comment]
@benmccann I think this was fixed potentially with SB 7, but I will try right now.

**Comment by benmccann** [comment]
Thanks for testing @brittneypostma. Since I haven't heard back, I'll assume this is fixed and will go ahead and close it. If that's incorrect we can reopen if we can get a reproduction

**Comment by brittneypostma** [comment]
Sorry @benmccann, I did start a [repro](https://github.com/brittneypostma/storybook-csf-jest-repro), but got distracted with something else and forgot to get back. This also included storyshots, so I can't speak to that specifically, but the Svelte CSF was working for me. I got a weird `unable to resolve $$` but a server restart seemed to fix that.

**Comment by arkmech** [comment]
Getting this issue now with Svelte 5 Beta:

SyntaxError: Unexpected token '<'
    at wrapSafe (node:internal/modules/cjs/loader:1383:18)
    at Module._compile (node:internal/modules/cjs/loader:1412:20)
    at Module._extensions..js (node:internal/modules/cjs/loader:1551:10)
    
Error: Cannot find module 'storybook/internal/common'
Require stack:
- /Users/me/Dev/project/node_modules/@storybook/addon-interactions/dist/preset.js
- /Users/me/Dev/project/node_modules/@storybook/addon-interactions/preset.js
- /Users/me/Dev/project/node_modules/@storybook/core-common/dist/index.js
- /Users/me/Dev/project/node_modules/@storybook/telemetry/dist/index.js
- /Users/me/Dev/project/node_modules/@storybook/cli/dist/generate.js
- /Users/me/Dev/project/node_modules/@storybook/cli/bin/index.js
- /Users/me/Dev/project/node_modules/storybook/index.js
