### ISSUE TITLE
[Bug] peer-dependencies include implicit dependencies

### ISSUE THREAD

**Issue by benbender** [storybookjs/addon-svelte-csf#52]
### Describe the bug

This package names several internal packages of `storybook` as peer-dependencies. Because those packages usually aren't installed explicitly, it may throw errors in certain package-managers. Below is an example of `pnpm`.

I would like to see those peer-deps removed. Would this be possible or is there any reason I may have overlooked for having them in the first place?

```
 WARN  Issues with peer dependencies found
.
└─┬ @storybook/addon-svelte-csf
  ├── ✕ missing peer @storybook/addons@^6.4.20
  ├── ✕ missing peer @storybook/api@^6.4.20
  ├── ✕ missing peer @storybook/client-api@^6.4.20
  ├── ✕ missing peer @storybook/client-logger@^6.4.20
  ├── ✕ missing peer @storybook/components@^6.4.20
  ├── ✕ missing peer @storybook/core-events@^6.4.20
  └── ✕ missing peer @storybook/theming@^6.4.20
Peer dependencies that should be installed:
  @storybook/addons@^6.4.20         @storybook/client-api@^6.4.20     @storybook/components@^6.4.20     @storybook/theming@^6.4.20
  @storybook/api@^6.4.20            @storybook/client-logger@^6.4.20  @storybook/core-events@^6.4.20
```

Thanks in advance!

**Comment by j3rem1e** [comment]
They come from the template used for generated this project.

@winkerVSbecks any idea why they are here ?

**Comment by winkerVSbecks** [comment]
@j3rem1e those are there to test your addon within its own repo. You can remove the ones your addon doesn't use. 

The idea is that the addon relies on these dependencies to work. This dependency comes from the end user's storybook install. Hence, they are listed as peer dependencies. It's kind of like a component library listing react as a peer dependency.

**Comment by benmccann** [comment]
`@storybook/svelte` is listed as a `peerDependency`:

https://github.com/storybookjs/addon-svelte-csf/blob/675be7f108f3522fcf701ad2397339cd68c67f10/package.json#L77

I think that should be enough because it's going to end up pulling these in as `dependencies`:

https://github.com/storybookjs/storybook/blob/7ca3a53b9caa8374b1143d66754807273260d100/app/svelte/package.json#L48

I think we only want to force users to put `@storybook/svelte` in their `package.json` and not all of Storybook's dependencies
