### ISSUE TITLE
[Bug] Does not work with Storybook 7.0.0-alpha.52 and storyStoreV6

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/addon-svelte-csf#79]
### Describe the bug

Seems not to work with Storybook 7.0.0-alpha.52

### Steps to reproduce the behavior

1. Disable storyStoreV7: `features.storyStoreV7: false`
2. Create a *.stories.svelte file like described in the docs
3. Configure the addon properly
4. Start Storybook (`yarn storybook`) -> No stories are rendered. An error occurs in the console:

```
Uncaught Error: unexpected configure() call
    at configure (index.mjs:2:1510)
    at O (index.mjs:1:328)
    at configStories (storybook-stories.js:16:7)
    at vite-app.js:88:5
```

### Expected behavior

Storybook should not fail

### Environment

 - OS: Mac
 - Node.js version: 16.18.1

### Additional context

Reproduction Repo: https://github.com/valentinpalkovic/repro-svelte-storybook-7.x

**Comment by JReinhold** [comment]
This works for me if I remove the disabling of `storyStoreV7`.

I know it shows a warning like `Cannot process svelte file with storyStoreV7: Button.stories.svelte`, but I think that is a false positive due to too strict checking. @shilman I feel like we've talked about this warning before, not taking into account addons that might add support for other extensions?

I might be a little rusty, but I don't think it's necessary to disable `storyStoreV7` to use this addon.
